# Generated by Django 3.1.6 on 2021-02-17 11:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='coursename', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='ikke oppgitt', max_length=30)),
                ('description', models.CharField(default='ikke oppgitt', max_length=200)),
                ('host', models.CharField(default='ikke oppgitt', max_length=30)),
                ('email', models.CharField(default='ikke oppgitt', max_length=50)),
                ('phone', models.CharField(default='ikke oppgitt', max_length=15)),
                ('capacity', models.IntegerField(default=0)),
                ('location', models.CharField(default='ikke oppgitt', max_length=30)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_event', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.FloatField(default=0)),
                ('split_bill', models.BooleanField(default=False)),
                ('contains_gluten', models.BooleanField(default=False)),
                ('contains_lactose', models.BooleanField(default=False)),
                ('contains_nut', models.BooleanField(default=False)),
                ('contains_shellfish', models.BooleanField(default=False)),
                ('other_allergens', models.CharField(default='ikke oppgitt', max_length=30)),
                ('courses', models.ManyToManyField(to='dinner.Course')),
            ],
        ),
    ]
