# Generated by Django 3.1.6 on 2021-02-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinner',
            name='host',
            field=models.CharField(default='ingen vet', max_length=30),
        ),
    ]
