# Generated by Django 3.1.6 on 2021-02-22 15:10

from django.db import migrations
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0002_auto_20210222_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinner',
            name='date_event',
            field=unixtimestampfield.fields.UnixTimeStampField(default=0.0),
        ),
    ]
