# Generated by Django 3.1.6 on 2021-02-09 13:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0002_dinner_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinner',
            name='beskrivelse',
            field=models.CharField(default='ikke oppgitt', max_length=200),
        ),
        migrations.AddField(
            model_name='dinner',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dinner',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='food',
            field=models.CharField(default='ikke oppgitt', max_length=30),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='host',
            field=models.CharField(default='ikke oppgitt', max_length=30),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='location',
            field=models.CharField(default='ikke oppgitt', max_length=30),
        ),
    ]
