# Generated by Django 3.1.6 on 2021-02-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0003_auto_20210209_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinner',
            name='title',
            field=models.CharField(default='ikke oppgitt', max_length=30),
        ),
    ]
