# Generated by Django 3.1.6 on 2021-02-11 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0004_dinner_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinner',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('dinner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='dinner.dinner')),
            ],
        ),
    ]
