# Generated by Django 3.1.6 on 2021-02-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0005_auto_20210211_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinner',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
