# Generated by Django 3.1.6 on 2021-03-20 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0005_auto_20210320_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinner',
            name='host_user',
        ),
        migrations.AddField(
            model_name='dinner',
            name='participants',
            field=models.ManyToManyField(related_name='_dinner_participants_+', to='dinner.User'),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='host',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dinner.user'),
        ),
    ]
