# Generated by Django 3.1.6 on 2021-02-11 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0007_auto_20210211_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dinner',
            old_name='alleries',
            new_name='allergies',
        ),
    ]
