# Generated by Django 3.1.6 on 2021-02-11 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0008_auto_20210211_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinner',
            name='allergies',
        ),
    ]
