# Generated by Django 3.1.6 on 2021-02-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0009_remove_dinner_allergies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.ManyToManyField(to='dinner.Dinner')),
            ],
        ),
    ]
