# Generated by Django 3.1.6 on 2021-02-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0010_allergy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allergy',
            name='title',
        ),
        migrations.AddField(
            model_name='allergy',
            name='desc',
            field=models.CharField(default='allerginavn', max_length=30),
        ),
        migrations.AddField(
            model_name='dinner',
            name='allergies',
            field=models.ManyToManyField(to='dinner.Allergy'),
        ),
    ]
