# Generated by Django 3.1.6 on 2021-02-11 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0011_auto_20210211_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allergy',
            old_name='desc',
            new_name='description',
        ),
    ]
