# Generated by Django 3.1.6 on 2021-02-11 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0012_auto_20210211_1108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allergy',
            options={'verbose_name_plural': 'Allergies'},
        ),
    ]
